CREATE TABLE `customRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestType` enum('recordatorios','empresarial') NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientEmail` varchar(320) NOT NULL,
	`clientPhone` varchar(20) NOT NULL,
	`clientCompany` varchar(255),
	`clientLocation` varchar(255) NOT NULL,
	`generalDescription` text NOT NULL,
	`candleType` varchar(255) NOT NULL,
	`quantity` int NOT NULL,
	`message` text,
	`colors` text,
	`style` varchar(255),
	`references` text,
	`event` varchar(255),
	`deliveryDate` varchar(255),
	`budget` varchar(255),
	`urgency` enum('normal','urgente') NOT NULL DEFAULT 'normal',
	`additionalComments` text,
	`status` enum('pendiente','revisada','completada','cancelada') NOT NULL DEFAULT 'pendiente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customRequests_id` PRIMARY KEY(`id`)
);
